export const BOOTCAMPS_LIST_REQUEST = 'BOOTCAMPS_LIST_REQUEST';
export const BOOTCAMPS_LIST_SUCCESS = 'BOOTCAMPS_LIST_SUCCESS';
export const BOOTCAMPS_LIST_FAIL = 'BOOTCAMPS_LIST_FAIL';
export const BOOTCAMPS_LIST_RESET = 'BOOTCAMPS_LIST_RESET';

export const BOOTCAMP_REQUEST = 'BOOTCAMP_REQUEST';
export const BOOTCAMP_SUCCESS = 'BOOTCAMP_SUCCESS';
export const BOOTCAMP_FAIL = 'BOOTCAMP_FAIL';

export const BOOTCAMP_REVIEWS_REQUEST = 'BOOTCAMP_REVIEWS_REQUEST';
export const BOOTCAMP_REVIEWS_SUCCESS = 'BOOT_CAMP_REVIEWS_SUCCESS';
export const BOOTCAMP_REVIEWS_FAIL = 'BOOT_CAMP_REVIEWS_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET';
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
