export const BOOTCAMPS_LIST_REQUEST = 'BOOTCAMPS_LIST_REQUEST';
export const BOOTCAMPS_LIST_SUCCESS = 'BOOTCAMPS_LIST_SUCCESS';
export const BOOTCAMPS_LIST_FAIL = 'BOOTCAMPS_LIST_FAIL';
export const BOOTCAMPS_LIST_RESET = 'BOOTCAMPS_LIST_RESET';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
